export const AUDIT_ACTION_OPTIONS = [
  { value: 'all', label: '全部动作' },
  { value: 'audit.export', label: '导出审计日志' },
  { value: 'impersonation.start', label: '开始代操作' },
  { value: 'impersonation.stop', label: '结束代操作' },
  { value: 'tenant.create', label: '创建租户' },
  { value: 'tenant.update', label: '更新租户' },
  { value: 'tenant.features.update', label: '更新租户能力' },
  { value: 'user.update', label: '更新平台用户' },
  { value: 'user.roles.update', label: '更新用户角色' },
  { value: 'member.invite-link.create', label: '创建邀请链接' },
  { value: 'member.invite-link.revoke', label: '撤销邀请链接' },
  { value: 'member.invite.email', label: '邮箱邀请成员' },
  { value: 'member.invite.resend', label: '重发邀请邮件' },
  { value: 'member.update', label: '更新成员' },
  { value: 'member.roles.update', label: '更新成员角色' },
  { value: 'tenant_role.create', label: '创建租户角色' },
  { value: 'tenant_role.update', label: '更新租户角色' },
  { value: 'tenant_role.delete', label: '删除租户角色' },
  { value: 'role.permissions.update', label: '更新角色权限' },
  { value: 'permission_module.create', label: '创建权限模块' },
  { value: 'permission_module.update', label: '更新权限模块' },
  { value: 'permission_module.delete', label: '删除权限模块' },
  { value: 'permission.create', label: '创建权限项' },
  { value: 'permission.update', label: '更新权限项' },
  { value: 'permission.delete', label: '删除权限项' },
  { value: 'billing.wallet.adjust', label: '计费调账' },
  { value: 'billing.package.write', label: 'SKU 变更' },
  { value: 'billing.recharge.refund', label: '充值退款' },
  { value: 'billing.coupon.write', label: '优惠券变更' },
  { value: 'billing.invoice.issue', label: '开具发票' },
  { value: 'billing.invoice.reject', label: '驳回发票' },
  { value: 'billing.wire_transfer.approve', label: '对公入账' },
  { value: 'billing.wire_transfer.reject', label: '驳回对公转账' },
] as const
